# Generated by Django 5.2.1 on 2025-05-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='estoque',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
