# Generated by Django 5.2.1 on 2025-05-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_veiculo_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(default='Desconhecida', max_length=60),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(default='Desconhecida', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(default='Desconhecida', max_length=60),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='Desconhecida', max_length=3),
        ),
        migrations.AddField(
            model_name='usuario',
            name='logradouro',
            field=models.CharField(default='Desconhecida', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(default='Desconhecida', max_length=10),
        ),
    ]
