# Generated by Django 5.2.1 on 2025-05-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_categoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
